### ISSUE TITLE
js后缀判断问题

### ISSUE THREAD

**Issue by oddjohn** [baihuibo/gulp-cmd-pack#3]
现在对后缀的判断比较弱，能否加上js后缀的判断，这样如require('foo.min')这样的才能加上js后缀

```
if (!path.extname(ret) || path.extname(ret) != '.js') {
        ret += '.js';
 }
```

**Comment by baihuibo** [comment]
多谢，这个问题已经修复
现在已经加入了对类似 `xxx.min.js` 的模块支持直接使用 `xxx.min` 标记来引用模块
